### PR TITLE
Fix #4 Unminify doesn't work for nested objects

### LINKED ISSUE #4: Unminify doesn't work for nested and null objects

### PR DESCRIPTION
**Pull request by alevkon**

### CODE REVIEW

**Review by mrister — CHANGES_REQUESTED** [review]
Needs a verification by test. please add a test to verify the fix.

**Comment by alevkon** [comment]
Here's the tests and another minor fix – of null objects.

**Review by mrister — APPROVED** [review]
🏅

**Review by ykhatal — APPROVED** [review]

**Comment by ykhatal** [comment]
@alevkon thanks for the contribution, :+1: 
@ofkindness @Spring3 bump

**Review by ofkindness — APPROVED** [review]

**Review by Spring3 — APPROVED** [review]

**Comment by mrister** [comment]
@alevkon , fix has been published to npm https://www.npmjs.com/package/json-minifier

**Comment by alevkon** [comment]
@mrister thanks a lot!

**Comment by mrister** [comment]
@alevkon thank you!

**Pull request merged**
